create table if not exists public.telegram_message_cleanup (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.telegram_chat_settings(chat_id) on delete cascade,
  message_id bigint not null,
  due_at timestamptz not null,
  deleted_at timestamptz,
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  unique (chat_id, message_id)
);

alter table public.telegram_message_cleanup enable row level security;

create policy "service_role_full_access_telegram_message_cleanup"
on public.telegram_message_cleanup
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create index if not exists idx_telegram_message_cleanup_due_at
on public.telegram_message_cleanup (due_at)
where deleted_at is null;
