create extension if not exists pgcrypto;

create table if not exists public.telegram_chat_settings (
  chat_id bigint primary key,
  daily_questions_enabled boolean not null default true,
  timezone text not null default 'Asia/Jerusalem',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_question_log (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.telegram_chat_settings(chat_id) on delete cascade,
  telegram_message_id bigint,
  question text not null,
  sent_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.daily_question_send_lock (
  chat_id bigint not null references public.telegram_chat_settings(chat_id) on delete cascade,
  send_date date not null,
  created_at timestamptz not null default now(),
  primary key (chat_id, send_date)
);

create table if not exists public.chat_context_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.telegram_chat_settings(chat_id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_telegram_chat_settings_updated_at
before update on public.telegram_chat_settings
for each row
execute function public.set_updated_at();

create trigger set_bot_state_updated_at
before update on public.bot_state
for each row
execute function public.set_updated_at();

alter table public.telegram_chat_settings enable row level security;
alter table public.daily_question_log enable row level security;
alter table public.daily_question_send_lock enable row level security;
alter table public.chat_context_messages enable row level security;
alter table public.bot_state enable row level security;

create policy "service_role_full_access_telegram_chat_settings"
on public.telegram_chat_settings
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service_role_full_access_daily_question_log"
on public.daily_question_log
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service_role_full_access_daily_question_send_lock"
on public.daily_question_send_lock
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service_role_full_access_chat_context_messages"
on public.chat_context_messages
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create policy "service_role_full_access_bot_state"
on public.bot_state
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create index if not exists idx_chat_context_messages_chat_created_at
on public.chat_context_messages (chat_id, created_at);
