create table if not exists public.interview_questions (
  id bigint generated by default as identity primary key,
  question text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.interview_questions enable row level security;

create policy "service_role_full_access_interview_questions"
on public.interview_questions
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

insert into public.interview_questions (question)
values
  ('Какие существуют типы данных в JavaScript и как их объявлять?'),
  ('Что такое лексическая область видимости в JavaScript?'),
  ('Какие основные методы массивов существуют в JavaScript?'),
  ('Что такое объекты в JavaScript? Как работать с их свойствами?'),
  ('Что такое Map и Set в JavaScript и TypeScript и как их использовать?'),
  ('Чем отличаются function expression, function declaration, arrow function и IIFE?'),
  ('Что такое hoisting в JavaScript?'),
  ('Что такое замыкание (closure) и как оно работает?'),
  ('Как работает this в JavaScript?'),
  ('Как использовать Call, Bind и Apply?'),
  ('Что такое классы в JavaScript и как работают статические методы?'),
  ('Что такое Promise и как использовать async/await?'),
  ('Что такое Event Loop в JavaScript?'),
  ('Что такое очередь задач и микротаски?'),
  ('Какие способы выполнения асинхронного кода существуют?'),
  ('Что такое proto / prototype и как работает прототипное наследование?'),
  ('Как происходит приведение типов данных в JavaScript?'),
  ('Что такое каррирование и как его использовать?'),
  ('В чем разница между модулями и стандартным экспортом/импортом (ESM)?'),
  ('Что такое полифиллы и когда их используют?'),
  ('Что такое итераторы и как сделать объект итерируемым?'),
  ('Как написать полифил для forEach?'),
  ('Как работает сборщик мусора в JavaScript?')
on conflict (question) do nothing;
